class Infinite_Lagrange:
    def __init__(self) -> None:
        self.__weapon_traits = {
            "anti-aircraft_special_ammo":"Switches to Special Ammo when striking an aircraft target, increasing the Damage Per Hit by an additional 50",
            "anti-aircraft_counterattack":"Can counterattack the enemy aerial targets that attacks me",
            "anti-aircraft_cycle":"The Weapon's operational efficiiency is increased when striking an aircraft target, reducing CD by an additional 25%",
            "anti-aircraft_support":"Can attack the enemy aerial target that targets friendly ships in the same row",
            "anti-aircraft_high-speed_strike":"Utilizes the High-Speed Strike mode when striking an aircraft target, reducing the duration of the strikes by an additional 10%",

            "interception_capability":"Has a chance to intercept Target yourself missiles or torpedoes",

            "attack_against_systems":"Has a chance to deal damage to the target's systems. Targeted systems will not include those ot in the Attack Priority.",

            "crit":"Has a 10% chance to deal an additional 120% Crit Damage to the target",
            } # Reestructurar para admitir valores. Quizá enfocarlo a función con return.

        self.__ships = {
            "utility":{
                "small_utility_ship":{
                    "storage":1500,
                    "engineering":300,
                    "mining_speed":10000,
                    "hp":4590,
                    "cruising_speed":400,
                    "warp_speed":2000,
                    "active_service":20
                },
                "medium_utility_ship":{
                    "storage":8000,
                    "engineering":1000,
                    "mining_speed":34000,
                    "hp":12180,
                    "cruising_speed":300,
                    "warp_speed":1500,
                    "active_service":20
                },

                "large_utility_ship":{
                    "storage":95000,
                    "engineering":3500,
                    "mining_speed":80000,
                    "hp":32190,
                    "cruising_speed":250,
                    "warp_speed":1250,
                    "active_service":20
                },
            },
            "fighter":{},
            "corvette":{},
            "frigate":{
                "fg300":{
                    "multi_role_type":{
                        "anti-ship_fire":1157,
                        "air_defense":607,
                        "siege_fire":270,
                                            
                        "hp":10530,
                        "defensive_capabilities":{
                            "armor":{
                                "basic":5,
                                "hp_recovery_bonus":"+0.25%"
                            },
                            "energy_shield":{
                                "basic":0
                            }
                        },

                        "cruising_speed":1000,
                        "warp_speed":5000,
                        "active_service":15,
                        "position":"middle_row",
                                            
                        "production_info":{
                            "metal_cost":7990,
                            "crystal_cost":540,
                            "deuterium_cost":110,
                            "build_time":"00:14:30",
                            "storage":2000,
                            "engineering":0,
                            "mining_level":0
                        },
                                            
                        "weapons":{
                            "fg300_generic_battery_system":{
                                "fg300-sg-1150":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"small_ship",
                                    "damage_per_hit":25,
                                    "lock-on_efficiency":"10.0%",
                                    "module_traits":[
                                        (self.__weapon_traits['anti-aircraft_special_ammo']),
                                        (self.__weapon_traits['anti-aircraft_counterattack']),
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "anti-ship_fire":(
                                                "1157/min",
                                                (1,"destroyer"),
                                                (1,"frigate"),
                                            ),
                                            "air_defense":(
                                                "607/min",
                                                (2,"corvette"),
                                                (3,"fighter"),
                                            ),
                                            "siege_fire":(
                                                "270/min",
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":"3s",
                                            "attacks_per_round":"1x3",
                                            "cooldown":"3.7s",
                                            "lock-on_time":"3s",
                                        },
                                    },
                                },
                            },
                        },
                        "special_module":{
                        },
                    },
                    "armored_type":{
                        "anti-ship_fire":771,
                        "air_defense":678,
                        "siege_fire":180,
                                            
                        "hp":12540,
                        "defensive_capabilities":{
                            "armor":{
                                "basic":15,
                                "hp_recovery_bonus":"+1.50%",
                            },
                            "energy_shield":{
                                "basic":0,
                            },
                        },

                        "cruising_speed":900,
                        "warp_speed":4500,
                        "active_service":15,
                        "position":"front_row",
                                            
                        "production_info":{
                            "metal_cost":10500,
                            "crystal_cost":670,
                            "deuterium_cost":140,
                            "build_time":"00:18:20",
                            "storage":1500,
                            "engineering":0,
                            "mining_level":0,
                        },
                                            
                        "weapons":{
                            "fg300_generic_battery_system":{
                                "fg300-sg-1150":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"small_ship",
                                    "damage_per_hit":25,
                                    "lock-on_efficiency":"10.0%",
                                    "module_traits":[
                                        (self.__weapon_traits['anti-aircraft_special_ammo']),
                                        (self.__weapon_traits['anti-aircraft_counterattack']),
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "anti-ship_fire":(
                                                "771/min",
                                                (1,"destroyer"),
                                                (1,"frigate")
                                            ),
                                            "air_defense":(
                                                "462/min",
                                                (2,"corvette"),
                                                (3,"fighter")
                                            ),
                                            "siege_fire":(
                                                "180/min"
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":"3s",
                                            "attacks_per_round":"1x3",
                                            "cooldown":"4s",
                                            "lock-on_time":"3s"
                                        },
                                    },
                                },
                                "sg-330b":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"aircraft",
                                    "damage_per_hit":15,
                                    "lock-on_efficiency":"45.0%",
                                    "module_traits":[
                                        (self.__weapon_traits['anti-aircraft_special_ammo']),
                                        (self.__weapon_traits['anti-aircraft_counterattack']),
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "air_defense":(
                                                "216/min",
                                                (1,"corvette"),
                                                (2,"fighter"),
                                            ),
                                        },
                                        "module_stats":{
                                            "attacks_per_round":"1x1",
                                            "cooldown":"3s",
                                            "lock-on_time":"2s",
                                        }
                                    }
                                },
                            },
                        },
                        "special_module":{
                        },
                    },
                    "recon_type":{
                        "anti-ship_fire":385,
                        "air_defense":505,
                        "siege_fire":90,
                                            
                        "hp":12540,
                        "defensive_capabilities":{
                            "armor":{
                                "basic":5,
                                "hp_recovery_bonus":"+0.25%"
                            },
                            "energy_shield":{
                                "basic":0
                            }
                        },

                        "cruising_speed":1040,
                        "warp_speed":5200,
                        "active_service":15,
                        "position":"middle_row",
                                            
                        "production_info":{
                            "metal_cost":6250,
                            "crystal_cost":590,
                            "deuterium_cost":140,
                            "build_time":"00:17:20",
                            "storage":2200,
                            "engineering":0,
                            "mining_level":0
                        },
                                            
                        "weapons":{
                            "fg300_generic_battery_system":{
                                "fg300-sg-1150":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"small_ship",
                                    "damage_per_hit":25,
                                    "lock-on_efficiency":"10.0%",
                                    "module_traits":[
                                        (self.__weapon_traits['anti-aircraft_special_ammo']),
                                        (self.__weapon_traits['anti-aircraft_counterattack']),
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "anti-ship_fire":(
                                                "385/min",
                                                (1,"destroyer"),
                                                (1,"frigate"),
                                            ),
                                            "air_defense":(
                                                "289/min",
                                                (2,"corvette"),
                                                (3,"fighter"),
                                            ),
                                            "siege_fire":(
                                                "90/min",
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":"3s",
                                            "attacks_per_round":"1x3",
                                            "cooldown":"4s",
                                            "lock-on_time":"3s",
                                        },
                                    },
                                },
                                "sg-330b":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"aircraft",
                                    "damage_per_hit":15,
                                    "lock-on_efficiency":"45.0%",
                                    "module_traits":[
                                        (self.__weapon_traits['anti-aircraft_special_ammo']),
                                        (self.__weapon_traits['anti-aircraft_counterattack']),
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "air_defense":(
                                                "216/min",
                                                (1,"corvette"),
                                                (2,"fighter"),
                                            ),
                                        },
                                        "module_stats":{
                                            "attacks_per_round":"1x1",
                                            "cooldown":"3s",
                                            "lock-on_time":"2s",
                                        },
                                    },
                                },
                            },
                        },
                        "special_module":{
                        },
                    },
                },
                "noma_m470":{
                    "siege_type":{
                        "anti-ship_fire":296,
                        "air_defense":72,
                        "siege_fire":1650,
                                            
                        "hp":14000,
                        "defensive_capabilities":{
                            "armor":{
                                "basic":5,
                                "hp_recovery_bonus":"+0.25%"
                            },
                            "energy_shield":{
                                "basic":0
                            }
                        },

                        "cruising_speed":800,
                        "warp_speed":4000,
                        "active_service":10,
                        "position":"back_row",
                                            
                        "production_info":{
                            "metal_cost":8150,
                            "crystal_cost":660,
                            "deuterium_cost":130,
                            "build_time":"00:17:30",
                            "storage":2200,
                            "engineering":0,
                            "mining_level":0
                        },
                                            
                        "weapons":{
                            "generic_battery_system":{
                                "mk1-bg-160_fortress":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"aircraft",
                                    "damage_per_hit":15,
                                    "lock-on_efficiency":0,
                                    "module_traits":[
                                        (self.__weapon_traits['anti-aircraft_counterattack']),
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "anti-ship_fire":(
                                                "200/min",
                                                (3,"destroyer"),
                                                (3,"frigate"),
                                            ),
                                            "air_defense":(
                                                "72/min",
                                                (1,"corvette"),
                                                (2,"fighter"),
                                            ),
                                            "siege_fire":(
                                                "138/min",
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":"3s",
                                            "attacks_per_round":"1x3",
                                            "cooldown":"6s",
                                            "lock-on_time":"2s",
                                        },
                                    },
                                },
                            },
                        },
                        "special_module":{
                            "siege_uav_support_system":{
                                "cst-4":{
                                    "carry_siege_uavs":"Siege UAV capacity: 1",
                                    "prioritized_target":"Building",
                                    "damage_per_hit":630,
                                    "module_traits":[
                                        (self.__weapon_traits['attack_against_systems'],
                                        {"attack_priority":{
                                            1,"command_system","high"}}), # attack_priority:(index, system, efficiency)
                                    ],
                                     "module_info":{
                                        "attack_priority":{
                                            "siege_fire":(
                                                "1512/min",
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":"10s",
                                            "attacks_per_round":"1x1",
                                            "cooldown":"15s",
                                            "lock-on_time":"8s",
                                        },
                                    },
                                },
                            },
                        },
                    },
                    "anti-aircraft_type":{
                        "anti-ship_fire":200,
                        "air_defense":2376,
                        "siege_fire":138,
                                            
                        "hp":14000,
                        "defensive_capabilities":{
                            "armor":{
                                "basic":5,
                                "hp_recovery_bonus":"+0.25%"
                            },
                            "energy_shield":{
                                "basic":0
                            }
                        },

                        "cruising_speed":800,
                        "warp_speed":4000,
                        "active_service":10,
                        "position":"back_row",
                                            
                        "production_info":{
                            "metal_cost":9440,
                            "crystal_cost":560,
                            "deuterium_cost":320,
                            "build_time":"00:26:50",
                            "storage":2000,
                            "engineering":0,
                            "mining_level":0
                        },
                                            
                        "weapons":{
                            "generic_battery_system":{
                                "mk1-bg-160_fortress":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"aircraft",
                                    "damage_per_hit":15,
                                    "lock-on_efficiency":0,
                                    "module_traits":[
                                        (self.__weapon_traits['anti-aircraft_counterattack']),
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "anti-ship_fire":(
                                                "200/min",
                                                (3,"destroyer"),
                                                (3,"frigate"),
                                            ),
                                            "air_defense":(
                                                "72/min",
                                                (1,"corvette"),
                                                (2,"fighter"),
                                            ),
                                            "siege_fire":(
                                                "138/min",
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":"3s",
                                            "attacks_per_round":"1x3",
                                            "cooldown":"6s",
                                            "lock-on_time":"2s",
                                        },
                                    },
                                },
                            },
                        },
                        "special_module":{
                            "anti-aircraft_uav_support_system":{
                                "crt-4":{
                                    "carry_anti-aircraft_uavs":"Anti-Aircraft UAV capacity: 1",
                                    "damage_type":"projectile",
                                    "prioritized_target":"aircraft",
                                    "damage_per_hit":30,
                                    "module_traits":[
                                        (self.__weapon_traits['anti-aircraft_counterattack']),
                                    ],
                                     "module_info":{
                                        "attack_priority":{
                                            "air_defense":(
                                                "2304/min",
                                                (1, "fighter"),
                                                (2, "corvette"),
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":0,
                                            "attacks_per_round":"4x1",
                                            "cooldown":"3s",
                                            "lock-on_time":"3s",
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
                "mare_nubium":{
                    "assault_type":{
                        "anti-ship_fire":953,
                        "air_defense":0,
                        "siege_fire":1532,
                                            
                        "hp":9030,
                        "defensive_capabilities":{
                            "armor":{
                                "basic":5,
                                "hp_recovery_bonus":"+0.25%"
                            },
                            "energy_shield":{
                                "basic":0
                            }
                        },

                        "cruising_speed":900,
                        "warp_speed":4500,
                        "active_service":10,
                        "position":"back_row",
                                            
                        "production_info":{
                            "metal_cost":10280,
                            "crystal_cost":630,
                            "deuterium_cost":130,
                            "build_time":"00:17:00",
                            "storage":1700,
                            "engineering":0,
                            "mining_level":0
                        },
                                            
                        "weapons":{
                            "missile_support_system":{
                                "am-2x138":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"small_ship",
                                    "damage_per_hit":60,
                                    "lock-on_efficiency":0,
                                    "module_traits":[
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "anti-ship_fire":(
                                                "857/min",
                                                (1,"destroyer"),
                                                (1,"frigate"),
                                            ),
                                            "siege_fire":(
                                                "20/min",
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":"2s",
                                            "attacks_per_round":"1x2",
                                            "cooldown":"5s",
                                            "lock-on_time":"3s",
                                        },
                                    },
                                },
                            },
                        },
                        "special_module":{
                            "assault_landing_uav_system":{
                                "cst-2":{
                                    "carry_siege_uavs":"Siege UAV capacity: 1",
                                    "prioritized_target":"Building",
                                    "damage_per_hit":630,
                                    "module_traits":[
                                        (self.__weapon_traits['attack_against_systems'],
                                        {"attack_priority":{
                                            1,"command_system","high"}}), # attack_priority:(index, system, efficiency)
                                    ],
                                     "module_info":{
                                        "attack_priority":{
                                            "siege_fire":(
                                                "1512/min",
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":"10s",
                                            "attacks_per_round":"1x1",
                                            "cooldown":"15s",
                                            "lock-on_time":"8s",
                                        },
                                    },
                                },
                            },
                        },
                    },
                    "anti-aircraft_type":{
                        "anti-ship_fire":685,
                        "air_defense":3008,
                        "siege_fire":0,
                                            
                        "hp":9030,
                        "defensive_capabilities":{
                            "armor":{
                                "basic":5,
                                "hp_recovery_bonus":"+0.25%"
                            },
                            "energy_shield":{
                                "basic":0
                            }
                        },

                        "cruising_speed":900,
                        "warp_speed":4500,
                        "active_service":"?",
                        "position":"middle_row",
                                            
                        "production_info":{
                            "metal_cost":9430,
                            "crystal_cost":590,
                            "deuterium_cost":190,
                            "build_time":"00:20:50",
                            "storage":1800,
                            "engineering":0,
                            "mining_level":0
                        },
                                            
                        "weapons":{
                            "missile_support_system":{
                                "am-2x1388":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"aircraft",
                                    "damage_per_hit":50,
                                    "lock-on_efficiency":"60.0%",
                                    "module_traits":[
                                        (self.__weapon_traits['anti-aircraft_counterattack']),
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "anti-ship_fire":(
                                                "685/min",
                                                (3,"destroyer"),
                                                (3,"frigate"),
                                            ),
                                            "air_defense":(
                                                "128/min",
                                                (1,"corvette"),
                                                (2,"fighter"),
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":"2s",
                                            "attacks_per_round":"1x2",
                                            "cooldown":"5s",
                                            "lock-on_time":"3s",
                                        },
                                    },
                                },
                            },
                        },
                        "special_module":{
                            "anti-aircraft_uav_support_system":{
                                "cat-2":{
                                    "carry_anti-aircraft_uavs":"Anti-Aircraft UAV capacity: 1",
                                    "damage_type":"projectile",
                                    "prioritized_target":"aircraft",
                                    "damage_per_hit":25,
                                    "module_traits":[
                                        (self.__weapon_traits['anti-aircraft_counterattack']),
                                    ],
                                     "module_info":{
                                        "attack_priority":{
                                            "air_defense":(
                                                "2880/min",
                                                (1, "fighter"),
                                                (2, "corvette"),
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":0,
                                            "attacks_per_round":"4x1",
                                            "cooldown":"2s",
                                            "lock-on_time":"2s",
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
                "mare_tranquillitatis":{
                    "integrated_type":{
                        "anti-ship_fire":1896,
                        "air_defense":811,
                        "siege_fire":328,
                                            
                        "hp":12360,
                        "defensive_capabilities":{
                            "armor":{
                                "basic":5,
                                "hp_recovery_bonus":"+0.25%"
                            },
                            "energy_shield":{
                                "basic":0
                            }
                        },

                        "cruising_speed":1000,
                        "warp_speed":5000,
                        "active_service":10,
                        "position":"middle_row",
                                            
                        "production_info":{
                            "metal_cost":8470,
                            "crystal_cost":700,
                            "deuterium_cost":120,
                            "build_time":"00:17:00",
                            "storage":1700,
                            "engineering":0,
                            "mining_level":0
                        },
                                            
                        "weapons":{
                            "cross_integrated_cannon_system":{
                                "mk2-ag-260a_cross":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"aircraft",
                                    "damage_per_hit":25,
                                    "lock-on_efficiency":0,
                                    "module_traits":[
                                        (self.__weapon_traits['anti-aircraft_special_ammo']),
                                        (self.__weapon_traits['anti-aircraft_counterattack']),
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "anti-ship_fire":(
                                                "771/min",
                                                (3,"destroyer"),
                                                (3,"frigate"),
                                            ),
                                            "air_defense":(
                                                "405/min",
                                                (1,"corvette"),
                                                (2,"fighter"),
                                            ),
                                            "siege_fire":(
                                                "180/min",
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":0,
                                            "attacks_per_round":"2x1",
                                            "cooldown":"7s",
                                            "lock-on_time":"3s",
                                        },
                                    },
                                },
                            },
                            "eternal_polaris_projectile_launching_system":{
                                "mk1-am-3x180_eternal_polaris":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"aircraft",
                                    "damage_per_hit":60,
                                    "lock-on_efficiency":0,
                                    "module_traits":[
                                        (self.__weapon_traits['anti-aircraft_special_ammo']),
                                        (self.__weapon_traits['anti-aircraft_cycle']),
                                        (self.__weapon_traits['anti-aircraft_support']),
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "anti-ship_fire":(
                                                "1125/min",
                                                (3,"destroyer"),
                                                (3,"frigate"),
                                            ),
                                            "air_defense":(
                                                "406/min",
                                                (1,"corvette"),
                                                (2,"fighter"),
                                            ),
                                            "siege_fire":(
                                                "148/min",
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":"3s",
                                            "attacks_per_round":"1x3",
                                            "cooldown":"13s",
                                            "lock-on_time":"4s",
                                        },
                                    },
                                },
                            },
                        },
                        
                    },
                    "anti-aircraft_type":{
                        "anti-ship_fire":535,
                        "air_defense":944,
                        "siege_fire":120,
                                            
                        "hp":12360,
                        "defensive_capabilities":{
                            "armor":{
                                "basic":5,
                                "hp_recovery_bonus":"+0.25%"
                            },
                            "energy_shield":{
                                "basic":0
                            }
                        },

                        "cruising_speed":1000,
                        "warp_speed":5000,
                        "active_service":"?",
                        "position":"middle_row",
                                            
                        "production_info":{
                            "metal_cost":9510,
                            "crystal_cost":1070,
                            "deuterium_cost":300,
                            "build_time":"00:33:40",
                            "storage":2000,
                            "engineering":0,
                            "mining_level":0
                        },
                                            
                        "weapons":{
                            "generic_battery_system":{
                                "ag-260":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"aircraft",
                                    "damage_per_hit":10,
                                    "lock-on_efficiency":0,
                                    "module_traits":[
                                        (self.__weapon_traits['anti-aircraft_special_ammo']),
                                        (self.__weapon_traits['anti-aircraft_cycle']),
                                        (self.__weapon_traits['anti-aircraft_counterattack']),
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "anti-ship_fire":(
                                                "120/min",
                                                (3,"destroyer"),
                                                (3,"frigate"),
                                            ),
                                            "air_defense":(
                                                "399/min",
                                                (1,"corvette"),
                                                (2,"fighter"),
                                            ),
                                            "siege_fire":(
                                                "120/min",
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":0,
                                            "attacks_per_round":"2x1",
                                            "cooldown":"2s",
                                            "lock-on_time":"3s",
                                        },
                                    },
                                },
                            },
                            "eternal_polaris_projectile_launching_system":{
                                "mk1-am-3x180b_eternal_polaris":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"aircraft",
                                    "damage_per_hit":20,
                                    "lock-on_efficiency":"60.0%",
                                    "module_traits":[
                                        (self.__weapon_traits['anti-aircraft_special_ammo']),
                                        (self.__weapon_traits['anti-aircraft_counterattack']),
                                        (self.__weapon_traits['interception_capability'], "Low"),
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "anti-ship_fire":(
                                                "415/min",
                                                (3,"destroyer"),
                                                (3,"frigate"),
                                            ),
                                            "air_defense":(
                                                "545/min",
                                                (1,"corvette"),
                                                (2,"fighter"),
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":"3s",
                                            "attacks_per_round":"1x3",
                                            "cooldown":"10s",
                                            "lock-on_time":"4s",
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
                "mare_serenitatis":{
                    "anti-ship_type":{
                        "anti-ship_fire":3385,
                        "air_defense":199,
                        "siege_fire":951,
                                            
                        "hp":14970,
                        "defensive_capabilities":{
                            "armor":{
                                "basic":5,
                                "hp_recovery_bonus":"+0.25%"
                            },
                            "energy_shield":{
                                "basic":0
                            }
                        },

                        "cruising_speed":900,
                        "warp_speed":4500,
                        "active_service":10,
                        "position":"back_row",
                                            
                        "production_info":{
                            "metal_cost":15820,
                            "crystal_cost":910,
                            "deuterium_cost":170,
                            "build_time":"00:22:50",
                            "storage":2000,
                            "engineering":0,
                            "mining_level":0
                        },
                                            
                        "weapons":{
                            "eternal_polaris_mk_i-a1_projectile_launching_system":{
                                "at-360a_supernova_white":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"large_ship",
                                    "damage_per_hit":377,
                                    "lock-on_efficiency":0,
                                    "module_traits":[
                                        (self.__weapon_traits['attack_against_systems'],
                                        {"attack_priority":{
                                            1:("primary_weapon_system","low"),
                                            2:("propulsion_system","low")}}), # attack_priority:(index, system, efficiency)
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "anti-ship_fire":(
                                                "3085/min",
                                                (1,"carrier"),
                                                (1,"battlecruiser"),
                                                (1,"cruiser"),
                                            ),
                                            "siege_fire":(
                                                "951/min",
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":0,
                                            "attacks_per_round":"1x1",
                                            "cooldown":"7s",
                                            "lock-on_time":"4s",
                                        },
                                    },
                                },
                            },
                            "cross_integrated_cannon_system":{
                                "mk1-ag-335b_cross":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"aircraft",
                                    "damage_per_hit":15,
                                    "lock-on_efficiency":"45.0%",
                                    "module_traits":[
                                        (self.__weapon_traits['anti-aircraft_special_ammo']),
                                        (self.__weapon_traits['anti-aircraft_cycle']),
                                        (self.__weapon_traits['anti-aircraft_high-speed_strike']),
                                        (self.__weapon_traits['anti-aircraft_counterattack']),
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "anti-ship_fire":(
                                                "300/min",
                                                (3,"destroyer"),
                                                (3,"frigate"),
                                            ),
                                            "air_defense":(
                                                "199/min",
                                                (1,"corvette"),
                                                (2,"fighter"),
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":"3s",
                                            "attacks_per_round":"1x3",
                                            "cooldown":"3s",
                                            "lock-on_time":"2s",
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
                "reliat":{
                    "anti-ship_type":{
                        "anti-ship_fire":2845,
                        "air_defense":459,
                        "siege_fire":370,
                                            
                        "hp":10530,
                        "defensive_capabilities":{
                            "armor":{
                                "basic":5,
                                "hp_recovery_bonus":"+0.25%"
                            },
                            "energy_shield":{
                                "basic":0
                            }
                        },

                        "cruising_speed":800,
                        "warp_speed":4000,
                        "active_service":10,
                        "position":"middle_row",
                                            
                        "production_info":{
                            "metal_cost":12490,
                            "crystal_cost":950,
                            "deuterium_cost":230,
                            "build_time":"00:28:30",
                            "storage":2000,
                            "engineering":0,
                            "mining_level":0
                        },
                                            
                        "weapons":{
                            "anti-ship_torpedo_system":{
                                "ct-240a_roland_iron_dwarf_k":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"small_ship",
                                    "damage_per_hit":75,
                                    "lock-on_efficiency":0,
                                    "module_traits":[
                                        (self.__weapon_traits['crit']),
                                        (self.__weapon_traits['anti-aircraft_counterattack']),
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "anti-ship_fire":(
                                                "2773/min",
                                                (1,"destroyer"),
                                                (1,"frigate"),
                                            ),
                                            "air_defense":(
                                                "384/min",
                                                (2,"corvette"),
                                                (3,"fighter"),
                                            ),
                                            "siege_fire":(
                                                "320/min",
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":15,
                                            "attacks_per_round":"4x4",
                                            "cooldown":"21s",
                                            "lock-on_time":"3s",
                                        },
                                    },
                                },
                            },
                            "rapid-fire_battery_system":{
                                "cg-135":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"aircraft",
                                    "damage_per_hit":10,
                                    "lock-on_efficiency":"15.0%",
                                    "module_traits":[
                                        (self.__weapon_traits['anti-aircraft_counterattack']),
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "anti-ship_fire":(
                                                "72/min",
                                                (3,"destroyer"),
                                                (3,"frigate"),
                                            ),
                                            "air_defense":(
                                                "75/min",
                                                (1,"corvette"),
                                                (2,"fighter"),
                                            ),
                                            "siege_fire":(
                                                "50/min",  
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":0,
                                            "attacks_per_round":"2x1",
                                            "cooldown":"3.5s",
                                            "lock-on_time":"2s",
                                        },
                                    },
                                },
                            },
                        },
                    },
                    "torpedo_type":{
                        "anti-ship_fire":3088,
                        "air_defense":86,
                        "siege_fire":874,
                                            
                        "hp":10530,
                        "defensive_capabilities":{
                            "armor":{
                                "basic":5,
                                "hp_recovery_bonus":"+0.25%"
                            },
                            "energy_shield":{
                                "basic":0
                            }
                        },

                        "cruising_speed":800,
                        "warp_speed":4000,
                        "active_service":"?",
                        "position":"middle_row",
                                            
                        "production_info":{
                            "metal_cost":12190,
                            "crystal_cost":1190,
                            "deuterium_cost":220,
                            "build_time":"00:30:20",
                            "storage":1800,
                            "engineering":0,
                            "mining_level":0
                        },
                                            
                        "weapons":{
                            "anti-ship_torpedo_system":{
                                "ct-248a_roland_iron_dwarf_p":{
                                    "damage_type":"energy",
                                    "prioritized_target":"large_ship",
                                    "damage_per_hit":100,
                                    "lock-on_efficiency":0,
                                    "module_traits":[
                                        (self.__weapon_traits['crit']),
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "anti-ship_fire":(
                                                "2608/min",
                                                (1,"carrier"),
                                                (1,"battlecruiser"),
                                                (1,"cruiser"),
                                            ),
                                            "siege_fire":(
                                                "860/min",
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":5,
                                            "attacks_per_round":"1x5",
                                            "cooldown":"18s",
                                            "lock-on_time":"3s",
                                        },
                                    },
                                },
                            },
                            "rapid-fire_pulse_cannon_system":{
                                "cp-110":{
                                    "damage_type":"energy",
                                    "prioritized_target":"aircraft",
                                    "damage_per_hit":20,
                                    "lock-on_efficiency":0,
                                    "module_traits":[
                                        (self.__weapon_traits['anti-aircraft_special_ammo']),
                                        (self.__weapon_traits['anti-aircraft_counterattack']),
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "anti-ship_fire":(
                                                "480/min",
                                                (3,"destroyer"),
                                                (3,"frigate"),
                                            ),
                                            "air_defense":(
                                                "86/min",
                                                (1,"corvette"),
                                                (2,"fighter"),
                                            ),
                                            "siege_fire":(
                                                "14/min",
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":0,
                                            "attacks_per_round":"1x1",
                                            "cooldown":"5s",
                                            "lock-on_time":"3s",
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
                "carilion":{
                    "recon_type":{
                        "anti-ship_fire":1125,
                        "air_defense":361,
                        "siege_fire":315,
                                            
                        "hp":8340,
                        "defensive_capabilities":{
                            "armor":{
                                "basic":5,
                                "hp_recovery_bonus":"+0.25%"
                            },
                            "energy_shield":{
                                "basic":0
                            }
                        },

                        "cruising_speed":1040,
                        "warp_speed":5200,
                        "active_service":10,
                        "position":"front_row",
                                            
                        "production_info":{
                            "metal_cost":7810,
                            "crystal_cost":660,
                            "deuterium_cost":170,
                            "build_time":"00:20:30",
                            "storage":1800,
                            "engineering":0,
                            "mining_level":0
                        },
                                            
                        "weapons":{
                            "rapid-fire_anti-ship_cannon_system":{
                                "cg-1118a":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"small_ship",
                                    "damage_per_hit":35,
                                    "lock-on_efficiency":"10.0%",
                                    "module_traits":[
                                        (self.__weapon_traits['anti-aircraft_counterattack']),
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "anti-ship_fire":(
                                                "1125/min",
                                                (1,"destroyer"),
                                                (1,"frigate"),
                                            ),
                                            "air_defense":(
                                                "189/min",
                                                (2,"corvette"),
                                                (3,"fighter"),
                                            ),
                                            "siege_fire":(
                                                "315/min",
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":3,
                                            "attacks_per_round":"1x3",
                                            "cooldown":"5s",
                                            "lock-on_time":"3s",
                                        },
                                    },
                                },
                            },
                            "near-defense_cannon_system":{
                                "mk1-cg-628b/d_comet_tail":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"aircraft",
                                    "damage_per_hit":15,
                                    "module_traits":[
                                        (self.__weapon_traits['anti-aircraft_special_ammo']),
                                        (self.__weapon_traits['anti-aircraft_counterattack']),
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "air_defense":(
                                                "172/min",
                                                (1,"corvette"),
                                                (2,"fighter"),
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":"6s",
                                            "attacks_per_round":"1x6",
                                            "cooldown":"4s",
                                            "lock-on_time":"3s",
                                        },
                                    },
                                },
                            },
                        },
                    },
                    "heavy_cannon_type":{
                        "anti-ship_fire":2485,
                        "air_defense":96,
                        "siege_fire":540,
                                            
                        "hp":9840,
                        "defensive_capabilities":{
                            "armor":{
                                "basic":5,
                                "hp_recovery_bonus":"+0.25%"
                            },
                            "energy_shield":{
                                "basic":0
                            }
                        },

                        "cruising_speed":950,
                        "warp_speed":4750,
                        "active_service":"?",
                        "position":"middle_row",
                                            
                        "production_info":{
                            "metal_cost":8590,
                            "crystal_cost":630,
                            "deuterium_cost":120,
                            "build_time":"00:16:20",
                            "storage":1500,
                            "engineering":0,
                            "mining_level":0
                        },
                                            
                        "weapons":{
                            "carilion_heavy_cannon_system":{
                                "cg-2238_carilion_k":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"small_ship",
                                    "damage_per_hit":300,
                                    "lock-on_efficiency":0,
                                    "module_traits":[
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "anti-ship_fire":(
                                                "2485/min",
                                                (1,"destroyer"),
                                                (1,"frigate"),
                                                (2,"carrier"),
                                                (2,"battlecruiser"),
                                                (2,"cruiser"),
                                            ),
                                            "siege_fire":(
                                                "540/min",
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":0,
                                            "attacks_per_round":"2x1",
                                            "cooldown":"14s",
                                            "lock-on_time":"5s",
                                        },
                                    },
                                },
                            },
                            "near-defense_cannon_system":{
                                "mk2-cg-1118b_comet_tail":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"aircraft",
                                    "damage_per_hit":10,
                                    "lock-on_efficiency":"45.0%",
                                    "module_traits":[
                                        (self.__weapon_traits['anti-aircraft_counterattack']),
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "air_defense":(
                                                "96/min",
                                                (1,"corvette"),
                                                (2,"fighter"),
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":0,
                                            "attacks_per_round":"2x1",
                                            "cooldown":"3s",
                                            "lock-on_time":"2s",
                                        },
                                    },
                                },
                            },
                        },
                    },
                    "special_type":{
                        "anti-ship_fire":1125,
                        "air_defense":285,
                        "siege_fire":315,
                                            
                        "hp":9770,
                        "defensive_capabilities":{
                            "armor":{
                                "basic":5,
                                "hp_recovery_bonus":"+0.25%"
                            },
                            "energy_shield":{
                                "basic":0
                            }
                        },

                        "cruising_speed":1040,
                        "warp_speed":5200,
                        "active_service":"?",
                        "position":"front_row",
                                            
                        "production_info":{
                            "metal_cost":8930,
                            "crystal_cost":660,
                            "deuterium_cost":260,
                            "build_time":"00:25:50",
                            "storage":1200,
                            "engineering":0,
                            "mining_level":0
                        },
                                            
                        "weapons":{
                            "rapid-fire_anti-ship_cannon_system":{
                                "cg-1118a":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"small_ship",
                                    "damage_per_hit":35,
                                    "lock-on_efficiency":"10.0%",
                                    "module_traits":[
                                        (self.__weapon_traits['anti-aircraft_counterattack']),
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "anti-ship_fire":(
                                                "1125/min",
                                                (1,"destroyer"),
                                                (1,"frigate"),
                                            ),
                                            "air_defense":{
                                                "189/min",
                                                (2,"corvette"),
                                                (3,"fighter"),
                                            },
                                            "siege_fire":(
                                                "315/min",
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":"3s",
                                            "attacks_per_round":"1x3",
                                            "cooldown":"5s",
                                            "lock-on_time":"3s",
                                        },
                                    },
                                },
                            },
                            "near-defense_cannon_system":{
                                "mk2-cg-1118b_comet_tail":{
                                    "damage_type":"projectile",
                                    "prioritized_target":"aircraft",
                                    "damage_per_hit":10,
                                    "lock-on_efficiency":"45.0%",
                                    "module_traits":[
                                        (self.__weapon_traits['anti-aircraft_counterattack']),
                                    ],
                                                        
                                    "module_info":{
                                        "attack_priority":{
                                            "air_defense":(
                                                "96/min",
                                                (1,"corvette"),
                                                (2,"fighter"),
                                            ),
                                        },
                                        "module_stats":{
                                            "duration":0,
                                            "attacks_per_round":"2x1",
                                            "cooldown":"3s",
                                            "lock-on_time":"2s",
                                        },
                                    },
                                },
                            },
                        },
                    },
                }, # special_type tiene 2 special_module que deben ser reflejados
            },
            "destroyer":{},
            "cruiser":{},
            "battlecruiser":{},
            "carrier":{},

        }